version: '3.9'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: buy-and-sell_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - buy-and-sell_data:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: buy-and-sell_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@db:27017/

volumes:
  buy-and-sell_data:
